// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSA_Race_Review_API.Migrations
{
    [DbContext(typeof(ReviewContext))]
    [Migration("20200907230508_SecondCreate3")]
    partial class SecondCreate3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MSA_Race_Review_API.Race", b =>
                {
                    b.Property<int>("raceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("averageScore")
                        .HasColumnType("int");

                    b.Property<string>("championship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("raceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reviewId")
                        .HasColumnType("int");

                    b.Property<string>("track")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("raceId");

                    b.HasIndex("reviewId");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("MSA_Race_Review_API.Review", b =>
                {
                    b.Property<int>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("reviewScore")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("reviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("reviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("timeCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("upvotes")
                        .HasColumnType("int");

                    b.HasKey("reviewId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("MSA_Race_Review_API.Race", b =>
                {
                    b.HasOne("MSA_Race_Review_API.Review", null)
                        .WithMany("Race")
                        .HasForeignKey("reviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
